// This file was generated by Rcpp::compileAttributes
// Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

#include <Rcpp.h>

using namespace Rcpp;

// makeInserts
CharacterVector makeInserts(CharacterMatrix df, CharacterVector dfName, CharacterVector colNames);
RcppExport SEXP sqlinserts_makeInserts(SEXP dfSEXP, SEXP dfNameSEXP, SEXP colNamesSEXP) {
BEGIN_RCPP
    Rcpp::RObject __result;
    Rcpp::RNGScope __rngScope;
    Rcpp::traits::input_parameter< CharacterMatrix >::type df(dfSEXP);
    Rcpp::traits::input_parameter< CharacterVector >::type dfName(dfNameSEXP);
    Rcpp::traits::input_parameter< CharacterVector >::type colNames(colNamesSEXP);
    __result = Rcpp::wrap(makeInserts(df, dfName, colNames));
    return __result;
END_RCPP
}
