// This file was generated by Rcpp::compileAttributes
// Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

#include <Rcpp.h>

using namespace Rcpp;

// makeInserts
CharacterVector makeInserts(const CharacterMatrix df, CharacterVector dfName, CharacterVector colNames, CharacterVector colTypes);
RcppExport SEXP sqlinserts_makeInserts(SEXP dfSEXP, SEXP dfNameSEXP, SEXP colNamesSEXP, SEXP colTypesSEXP) {
BEGIN_RCPP
    Rcpp::RObject __result;
    Rcpp::RNGScope __rngScope;
    Rcpp::traits::input_parameter< const CharacterMatrix >::type df(dfSEXP);
    Rcpp::traits::input_parameter< CharacterVector >::type dfName(dfNameSEXP);
    Rcpp::traits::input_parameter< CharacterVector >::type colNames(colNamesSEXP);
    Rcpp::traits::input_parameter< CharacterVector >::type colTypes(colTypesSEXP);
    __result = Rcpp::wrap(makeInserts(df, dfName, colNames, colTypes));
    return __result;
END_RCPP
}
